### ISSUE TITLE
incorrect labels

### ISSUE THREAD

**Issue by joh10891** [developmentseed/label-maker#103]
I looked into why my models were training so poorly, and seem to have an issue with the labels. I'm trying to train a model to detect farmland. However, the tiles seem to be correctly labeled. I checked OSM, and the areas are appropriated labeled. For some reason, my tiles seem to make no sense with what they're labeled. Can't figure out any rhyme or reason why certain features are incorrectly labeled. For example, the golf course is classed as farmland, as are some random buildings. There are also far too few tiles labeled as agriculture: should be well over half of the AOI. 

I'm not quite sure what the issue would be. Perhaps I'm filtering incorrectly?
The snippet from the json I'm using is:
`'classes': [{ "name": "agriculture", "filter": ["has", "landuse", "farmland"] }]`

Here, blue is agriculture, green is non-ag.
<img width="596" alt="example2" src="https://user-images.githubusercontent.com/29440741/43624158-3bce8a76-96ab-11e8-98ec-0a4e888aea2e.png">

There should be far more agriculture tiles
<img width="242" alt="incorrect counts" src="https://user-images.githubusercontent.com/29440741/43624159-3bde4f56-96ab-11e8-875e-b74dc0330f58.png">

Here, green is ag, blue is non-ag.
<img width="601" alt="example1" src="https://user-images.githubusercontent.com/29440741/43624160-3becb604-96ab-11e8-803e-bc42c692f285.png">

**Comment by joh10891** [comment]
Looked it over, and I'm not 100% clear on the filtering syntax- perhaps it's where I'm hitting an issue. Checked out OSM and Mapbox filtering keys and classes, and not quite sure how they should be specified. Particularly 'landuse' Virtually all of the examples or use cases I've seen are roads/buildings filters. Thanks for the help, and label-maker seems like a very powerful tool for GIS'ers and image scientists to have!

**Comment by drewbo** [comment]
@joh10891 You're definitely right that we could use some more examples. In this case, the filter is almost there, you would need to change `has` to `==` (the former is a check to see if a feature has that property at all, the latter checks to see if the feature has the property with the given value). If you want to inspect the underlying `mbtiles` file a bit easier to see what the base data looks like, I recommend using [mbview](https://github.com/mapbox/mbview)

**Comment by joh10891** [comment]
Hmm, had tried `==` previously. But tried it again, and still got strangely few tiles with inaccurate labels. No clue what the problem could be! Once it gets sorted out, I'm more than happy to share my project if you'd like to add it to the examples section.

**Comment by joh10891** [comment]
For the sake of trial and error, I tried the following filters but still no success. No clue what the problem could be.
`"has", "landuse", "farmland"` (generates a few labels, but inaccurate)
`"has", "agriculture"` (doesn't work)
`"has", "class", "agriculture"` (doesn't work)
`"has", "class", "farmland"` (doesn't work)
`"has", "landuse=farmland"` (doesn't work)
`"==", "landuse", "farmland"` (generates a few labels, but inaccurate)
`"==", "landuse", "agriculture"` (doesn't work)
`"==", "class", "agriculture"` (doesn't work)

**Comment by drewbo** [comment]
The sixth entry looks correct. Do you know if all the data is labelled correctly in OpenStreetMap? You can check out the [Mapbox GL filters](https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter) and [OSM `landuse` tag options](https://wiki.openstreetmap.org/wiki/Key:landuse) for more context. I tried replicating over some farm area in Portugal and it all appears properly labelled (it matches the OSM data but not necessarily the satellite data):

**config.json**
```json
{
  "country": "portugal",
  "bounding_box": [-9.178047180175781,
              39.0525182700645,
              -9.134101867675781,
              39.07864158248181],
  "zoom": 16,
  "classes": [
    { "name": "Farmland", "filter": ["==", "landuse", "farmland"] }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=ACCESS_TOKEN",
  "background_ratio": 1,
  "ml_type": "classification"
}
```

**farmland in yellow over mapbox satellite**

<img width="855" alt="screen shot 2018-08-10 at 11 39 26 am" src="https://user-images.githubusercontent.com/7108211/43967368-350dec6c-9c92-11e8-9f2e-0afea76d9b48.png">


**selected area in OSM rendering (farmland in yellow)**


<img width="542" alt="screen shot 2018-08-10 at 11 38 51 am" src="https://user-images.githubusercontent.com/7108211/43967378-38f5e00a-9c92-11e8-931e-f55b5d63ee8e.png">

**Comment by joh10891** [comment]
Thank you! Your Portugal example prompted me to try other countries- for some reason, every other AOI outside of the US I've tried has worked with no mislabeled tiles. No idea why I can't get it to work in the US, but I'm just going to use non-US farmland for training data. I appreciate the help, Drew!
