### ISSUE TITLE
Preserving Coordinates during tf_od_predict script detection (.GeoTiff)

### ISSUE THREAD

**Issue by Geo-Trackers** [developmentseed/label-maker#130]
Is it possible to preserve the coordinates of the geo tif image tiles while running the tf_od_predict.py ?

Thank you 

Best, 
Suman

**Comment by Geoyi** [comment]
closing this, and if you have a same question, see [this comment](https://github.com/developmentseed/label-maker/issues/127#issuecomment-453638093)
