### ISSUE TITLE
0 tiles from `label-maker labels`

### ISSUE THREAD

**Issue by danstowell** [developmentseed/label-maker#134]
Hi - when I run a basic `download` and `labels` I get zero tiles, and I can't tell why. Is there some way that the script could help to diagnose?

FYI, when I run the togo example from the documentation I don't get the 1189 tiles shown in the documentation, I get:

```
 % label-maker labels -c togo-config.json          # exactly the same as the doc example, plus my mapbox API key
Determining labels for each tile
---
Roads: 11 tiles
Buildings: 10 tiles
Total tiles: 12
Writing out labels to data/labels.npz
```

Then when I run my own, which looks like this:

```
{
  "country": "united_kingdom",
  "bounding_box": [51.31258868168418,-0.440826416015625,51.68362528576683,0.23345947265625],
  "zoom": 12,
  "classes": [
    { "name": "Roads", "filter": ["has", "highway"] },
    { "name": "photovoltaic", "filter": ["==", "generator:method", "photovoltaic"] }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=API_KEY",
  "background_ratio": 1,
  "ml_type": "classification"
}
```

I get

```
 % label-maker labels            
Determining labels for each tile
---
Roads: 0 tiles
photovoltaic: 0 tiles
Total tiles: 54
Writing out labels to data/labels.npz
```

Yet the tag I'm querying for is indeed there in the data (see http://overpass-turbo.eu/s/GYQ).

I'd be grateful for any way I can diagnose this and get it up and running.

**Comment by drewbo** [comment]
@danstowell your togo output looks correct (the documentation output uses a different config). For the uk example, your bounding box coordinates are flipped (should have longitude first per http://devseed.com/label-maker/parameters.html)

**Comment by danstowell** [comment]
Thank you for spotting my error!
After fixing it, I still appear to get zero:

```
% label-maker download   
Saving QA tiles to data/united_kingdom.mbtiles
   100%      1.0 GiB     986.1 KiB/s            0:00:00 ETA    
% label-maker labels  
Determining labels for each tile
---
Roads: 0 tiles
photovoltaic: 0 tiles
Total tiles: 72
Writing out labels to data/labels.npz
```

(For completeness: my bbox is now specified as `  "bounding_box": [-0.440826416015625,51.31258868168418,0.23345947265625,51.68362528576683]`)

I note that this time I get 72 tiles rather than 54, so it's not reusing the stale data. (Is there any cache file one should delete before retrying? It definitely re-downloaded the QA tiles)

**Comment by drewbo** [comment]
@danstowell yes, you'll need to remove `data/united_kingdom-z12.mbtiles` (and maybe `data/united_kingdom.geojson` to be safe) and run `label-maker labels` again. Note that this is only true for changes to the bounding box, you can make class changes without deleting these files.

Expected output should be:
```sh
Roads: 72 tiles
photovoltaic: 28 tiles
Total tiles: 72
Writing out labels to data/labels.npz
```

Let me know if that helps!

**Comment by danstowell** [comment]
Got it, thanks. I now have the same output as you. Thanks for the patient answers

**Comment by NickElixir** [comment]
This error appears with me.
This my config.json:
```{
  "country": "russia",
  "bounding_box": [55.67794, 37.46674, 55.68805, 37.5451],
  "zoom": 17,
  "classes": [
    { "name": "Roads", "filter": ["has", "highway"] },
    { "name": "Buildings", "filter": ["has", "building"] }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token="
    + token,
  "background_ratio": 1,
  "ml_type": "classification"
}
```

I launched this bash-command:
```
dir_name = "moscow17"
!label-maker download --dest $dir_name --config config.json
!label-maker labels --dest $dir_name --config config.json
!label-maker preview -n 10 --dest $dir_name --config config.json
!label-maker images --dest $dir_name --config config.json
!label-maker package --dest $dir_name --config config.json
```
and got:
```
Saving QA tiles to moscow17/russia.mbtiles
   100%      5.5 GiB       3.5 MiB/s            0:00:00 ETA   
Retiling QA Tiles to zoom level 17 (takes a bit)
0 features, 10 bytes of geometry, 4 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
Determining labels for each tile
---
Roads: 0 features in 0 tiles
Buildings: 0 features in 0 tiles
Total tiles: 185
Writing out labels to moscow17/labels.npz
```
So, I tried the decision from @drewbo and deleted all files in directory except russia.mbtiles. I executed the code again and problem was not be solved.
So, what is the problem? I think config.json is correct, but maybe there is a mistake.

**Comment by drewbo** [comment]
@NickElixir the bounding box has the longitude and latitude values switched (so the bounding box is located in Iraq instead of Russia). You can check parameter details here: http://devseed.com/label-maker/parameters.html

**Comment by NickElixir** [comment]
Thanks, @drewbo! It was a childish mistake, now it works.
But retiling takes really much time. Near 8 hours. Is this normal or not?

**Comment by drewbo** [comment]
@NickElixir it really depends on the size of the bounding box and the density of the OSM data in that region. Unfortunately there isn't a perfect way to query OSM data for this project, in my understanding it's a tradeoff between two main options:
- [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API) allows for arbitrary queries on OSM data but each hosted instance has rate limits which I'd worry about exceeding for large tasks.
- [OSM QA Tiles](https://osmlab.github.io/osm-qa-tiles/) have all the necessary data per country but require post-processing because they are made available at zoom level 12.

Ultimately we went with the second option. To get the tile data at the zoom requested by the user, we:
- convert the `mbtiles` file to GeoJSON using `tippecanoe-decode`
- filter that using the input bounding box to speed up the following step
- retile at the desired zoom level using `tippecanoe`

It's a bit of a hack and in my mind is the weakest part of the library. Let me know if this is helpful information and if you have any other ideas about how to implement.

**Comment by NickElixir** [comment]
I got this problem again:
<code>
Yakutsk_Airport_16
Determining labels for each tile
Aerodrom: 0 tiles
Aeroway: 0 tiles
Apron: 0 tiles
Buildings: 0 tiles
Drystream: 0 tiles
Farmland: 0 tiles
Forest: 0 tiles
Grass: 0 tiles
Grassland: 0 tiles
Greenfield: 0 tiles
Heath: 0 tiles
Highway: 0 tiles
Landuse: 0 tiles
Motorway: 0 tiles
Natural: 0 tiles
Offices: 0 tiles
Offices: 0 tiles
Primary: 0 tiles
Residential: 0 tiles
River: 0 tiles
Riverbank: 0 tiles
Road: 0 tiles
Runway: 0 tiles
Scrub: 0 tiles
Secondary: 0 tiles
Stream: 0 tiles
Taxiway: 0 tiles
Tertiary: 0 tiles
Tree: 0 tiles
Trunk: 0 tiles
Waterway: 0 tiles
Wood: 0 tiles
Total tiles: 2964
</code>

<code>
{"country": "russia", "bounding_box": [113.93900146484376, 62.434698486328124, 114.13900146484374, 62.634698486328126], "zoom": 16, "classes": [{"name": "Aerodrom", "filter": ["has", "aerodrom"]}, {"name": "Aeroway", "filter": ["has", "aeroway"]}, {"name": "Apron", "filter": ["has", "apron"]}, {"name": "Buildings", "filter": ["has", "buildings"]}, {"name": "Drystream", "filter": ["has", "drystream"]}, {"name": "Farmland", "filter": ["has", "farmland"]}, {"name": "Forest", "filter": ["has", "forest"]}, {"name": "Grass", "filter": ["has", "grass"]}, {"name": "Grassland", "filter": ["has", "grassland"]}, {"name": "Greenfield", "filter": ["has", "greenfield"]}, {"name": "Heath", "filter": ["has", "heath"]}, {"name": "Highway", "filter": ["has", "highway"]}, {"name": "Landuse", "filter": ["has", "landuse"]}, {"name": "Motorway", "filter": ["has", "motorway"]}, {"name": "Natural", "filter": ["has", "natural"]}, {"name": "Offices", "filter": ["has", "offices"]}, {"name": "Offices", "filter": ["has", "offices"]}, {"name": "Primary", "filter": ["has", "primary"]}, {"name": "Residential", "filter": ["has", "residential"]}, {"name": "River", "filter": ["has", "river"]}, {"name": "Riverbank", "filter": ["has", "riverbank"]}, {"name": "Road", "filter": ["has", "road"]}, {"name": "Runway", "filter": ["has", "runway"]}, {"name": "Scrub", "filter": ["has", "scrub"]}, {"name": "Secondary", "filter": ["has", "secondary"]}, {"name": "Stream", "filter": ["has", "stream"]}, {"name": "Taxiway", "filter": ["has", "taxiway"]}, {"name": "Tertiary", "filter": ["has", "tertiary"]}, {"name": "Tree", "filter": ["has", "tree"]}, {"name": "Trunk", "filter": ["has", "trunk"]}, {"name": "Waterway", "filter": ["has", "waterway"]}, {"name": "Wood", "filter": ["has", "wood"]}], "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoiemVyb2x5bXAiLCJhIjoiY2p2NWJ2aW9rMDFyNTN5bzZlMTY3NmFucSJ9.SrPXLPkFpd22vCnYsSvxoA", "background_ratio": 1, "ml_type": "segmentation"}
</code>

So, the configuration is correct too. I tried to reset ...-z16.mbtiles and geojson, but it's not help. What can the problem be?

**Comment by NickElixir** [comment]
I found the problem: it was that I forget to copy "russia.mbtiles" to directory of Yakytsk Airport.
So, I have another question: how can I refer to "russia.mbtiles" which is located in parent directory for avoidance copying this file?

**Comment by drewbo** [comment]
@NickElixir unfortunately the folder structure is required right now when using the CLI. If you call the functions directly (e.g. `from label_maker.label import make_labels`) you can specify exact file paths.

It also looks like you will run into some issues with the OSM filters. The format `["has", "tag"]` only checks for the existence of a tag, not for any of its values. So this is suitable for things like `["has", "building"]` or `["has", "highway"]` but not much else. To match a specific tag and value combination, I'd recommend the `==` operator. Here is an example for matching [trees](https://wiki.openstreetmap.org/wiki/Tag:natural=tree): `["==", "natural", "tree"]`

Let me know if that all works

**Comment by NickElixir** [comment]
In this function I need to change only this code:
`mbtiles_file = op.join(dest_folder, '{}.mbtiles'.format(country))`
I don't need to import make_labels() function from library.
So, how can I edit library?
Can I use fork in GitHub and save label-maker CLI functionality or I can change label.py only on my computer for it?

**Comment by NickElixir** [comment]
@drewbo And thank you, using operator `==` is more effective
