### ISSUE TITLE
Update API parameters for Sentinel Hub

### ISSUE THREAD

**Issue by adbeda** [developmentseed/label-maker#139]
The API for Sentinel Hub has changed since [the example on how to access](https://github.com/developmentseed/label-maker/blob/master/examples/sentinel-hub.md)  imagery was written. Use the following config.json file to download, for instance, Sentinel-2 L1C imagery.

      {
       "country": "spain",
       "bounding_box": [
             -0.745697021484375,
              39.28010491220614,
             -0.3076171875,
              39.625788248139436
            ],
        "zoom": 14,
        "classes": [
         { "name": "Building", "filter": ["has", "building"] }
           ],
       "imagery": "http://services.sentinel-hub.com/ogc/wms/[WMS_ID]?SERVICE=WMS&REQUEST=GetMap&BBOX={bbox}&LAYERS=TRUE_COLOR&MAXCC=20&SHOWLOGO=false&VERSION=1.1.1&WIDTH=256&HEIGHT=256&FORMAT=image/jpeg&TIME=2016-01-29/2019-02-29&srs=EPSG%3A3857&NAME=Sentinel-2%20L1C",
       "background_ratio": 1,
       "ml_type": "segmentation"
     }

Dont forget to replace the `WMS_ID` value on `"http://services.sentinel-hub.com/ogc/wms/[WMS_ID]`, with your ID.

**Comment by drewbo** [comment]
Thanks, I think the former example will still work but only if the WMS configuration was set up with the older layer names. I'll make the update now
