### ISSUE TITLE
Tile images sometimes are corrupted

### ISSUE THREAD

**Issue by VicXue** [developmentseed/label-maker#141]
I'm not sure what happened when I downloaded tile images. Some of the downloaded images are corrupted. I used this config.json setup:

`{
  "country": "new_zealand",
  "bounding_box": [175.1848,-37.8868,175.4386,-37.6892],
  "zoom": 17,
  "classes": [
    {"name": "Populated Area", "filter": ["has", "building"]  }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoidmljeHVlIiwiYSI6ImNqeHRxbTk2dzB4N2ozbW50NTB5MzU5bDUifQ.HElp34ctd7HUI9i2vBoLMw",
  "background_ratio": 1,
  "ml_type": "segmentation"
}
`

In total, there are 1032 images downloaded and 345 of these images are corrupted. Two of the corrupted images can be visualized, as shown in below. The rest of the corrupted images cannot be opened.  
![129325-80375-17](https://user-images.githubusercontent.com/19631188/61103141-f146b900-a4c4-11e9-8a8d-8ea477a0d2f9.jpg)
![129326-80377-17](https://user-images.githubusercontent.com/19631188/61103143-f1df4f80-a4c4-11e9-83cd-519202635cae.jpg) 

It seems it does not matter what classes I'm trying to retrieve, the downloaded tile images always contain corrupted images in this area. I used to use a smaller bounding box and it worked fine. Can you please give it a try and tell me what your result is? I'm not sure if there is something wrong on my end.

Thank you.

**Comment by drewbo** [comment]
@VicXue in certain areas at higher resolution, the `mapbox.satellite` tileset doesn't have any data or returns lower quality imagery (black and white or lower resolution). We should definitely add better "handling" for this case but there isn't a way to prevent it outright (other than using another imagery endpoint)

**Comment by VicXue** [comment]
@drewbo Is there a way for users to choose their own imagery endpoint? Or will such functionality be in later releases?

**Comment by drewbo** [comment]
@VicXue yes, you can replace the `imagery` property in your `config.json` file with any valid XYZ tile endpoint or WMS endpoint (example for the latter shown [here](https://github.com/developmentseed/label-maker/blob/master/examples/sentinel-hub.md))

**Comment by VicXue** [comment]
@drewbo Great, thank you for your support.
