### ISSUE TITLE
Is anyone able to install label-maker on osx ? It requires a specific version of rasterio which can't seem to be installed. 

### ISSUE THREAD

**Issue by kunal732** [developmentseed/label-maker#145]
Label-maker requires rasterio==1.0a12. However every time i try to install that version with python3 i get 20 errors. Any of the other more recent versions of rasterio install fine. But label-maker always uninstalls those and tries to install 1.0a12 unfortunately. 

`257 warnings and 20 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: `

Just wanted to see if there are osx users who have been able to install label-maker and the specific version of it's dependency rasterio that it requires.

**Comment by drewbo** [comment]
What python version are you using @kunal732? I also get a clang build error on 3.7 against the pyclipper dependency; on 3.6.8 I was able to install correctly. At the same time, I would like to eventually update all the dependencies as have some automated builds to test for this as well

**Comment by kunal732** [comment]
@drewbo Currently on 3.7.4. I'll try a different version.

**Comment by kunal732** [comment]
@drewbo switching over to 3.6.8 solved the issue. Thank you

**Comment by drewbo** [comment]
I'll try to improve the install + build in the future with better testing + wheels but glad you have it working for now
