### ISSUE TITLE
Not able to install label-maker on mac using the command pip install label-maker?

### ISSUE THREAD

**Issue by PallawiSinghal** [developmentseed/label-maker#154]
Hi,
I am facing issue to install label-maker on my mac using the command pip install label-maker.
I am trying to install all the dependencies in an anaconda environment. Anaconda 4.0.1

**I am using python 3.6.9   and have installed  tippecanoe.**

**Please help. I have invested a lot of time just setting up the environment. 
Please provide a detail readme for the users.**

**I get the below error:**

bash-3.2$ conda install --file requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - protobuf==3.5.0.post1
  - pyclipper==1.0.6
  - rasterio==1.0a12
  - mercantile==1.0.0

Current channels:

  - https://conda.anaconda.org/abinit/osx-64
  - https://conda.anaconda.org/abinit/noarch
  - https://conda.anaconda.org/matsci/osx-64
  - https://conda.anaconda.org/matsci/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by drewbo** [comment]
Are you using pip or conda? Using both in conjunction can create some conflicts and many of our dependencies are not available directly through conda forge endpoints

**Comment by PallawiSinghal** [comment]
> Are you using pip or conda? Using both in conjunction can create some conflicts and many of our dependencies are not available directly through conda forge endpoints.


Thank you for the reply.
After installing all the dependencies with conda. I am left with 'rasterio[s3]' installation.
**Can you please help how we can install 'rasterio[s3]' on mac os.**

**Comment by PallawiSinghal** [comment]
**When I use this command : conda install -c https://conda.anaconda.org/ioos rasterio**

**I get this error:**

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                     /  

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package readline conflicts for:
python=3.6.0 -> readline=6.2
Package openssl conflicts for:
python=3.6.0 -> openssl=1.0
Package affine conflicts for:
rasterio -> affine[version='>=1.3.0']
Package zlib conflicts for:
python=3.6.0 -> zlib=1.2
Package snuggs conflicts for:
rasterio -> snuggs[version='>=1.2|>=1.4.1']
Package numpy conflicts for:
rasterio -> numpy[version='1.11.*|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.9.3,<2.0a0']
Package click conflicts for:
rasterio -> click[version='>=4,<8']
Package xz conflicts for:
python=3.6.0 -> xz=5.2
Package sqlite conflicts for:
python=3.6.0 -> sqlite=3.13
Package pip conflicts for:
python=3.6.0 -> pip
Package libcxx conflicts for:
rasterio -> libcxx[version='>=4.0.1|>=9.0.0']
Package boto3 conflicts for:
rasterio -> boto3[version='>=1.2.4']
Package tk conflicts for:
python=3.6.0 -> tk=8.5
Package setuptools conflicts for:
rasterio -> setuptools[version='>=0.9.8']
Package attrs conflicts for:
rasterio -> attrs[version='>=16.0.0']
Package enum34 conflicts for:
rasterio -> enum34
Package cligj conflicts for:
rasterio -> cligj[version='>=0.5']
Package proj4 conflicts for:
rasterio -> proj4[version='<6,>=5.2.0,<5.2.1.0a0']
Package click-plugins conflicts for:
rasterio -> click-plugins
Package gdal conflicts for:
rasterio -> gdal=2.1
Package libgdal conflicts for:
rasterio -> libgdal[version='2.4.*,>=2.4.2,<2.5.0a0|>=2.2.2,<2.3.0a0|>=2.2.4,<2.3.0a0|>=2.3.3,<2.4.0a0|>=2.4.1,<2.5.0a0|>=2.4.2,<2.5.0a0|>=3.0.1,<3.1.0a0|>=3.0.2,<3.1.0a0']

**Comment by drewbo** [comment]
Can you try the instructions on rasterio's [installation page](https://github.com/mapbox/rasterio/#binary-distributions):
```
conda install -c conda-forge rasterio
```

I'm not as familiar with conda so I'm not positive how to debug

**Comment by PallawiSinghal** [comment]
Finallly I was able to install it on linux.

using **sudo python -m pip install -r requirements.txt**
