### ISSUE TITLE
Background tile ratio 

### ISSUE THREAD

**Issue by martham93** [developmentseed/label-maker#158]
Currently background tile ratio only applies to single class `classification` data sets. https://github.com/developmentseed/label-maker/blob/master/label_maker/images.py#L62. 
We would like to expand adding a specific ratio of background tiles to `multi-class` `classification` data sets. This addition is key for our FFDA work, and will also help other users of label-maker. 

cc @wronk @drewbo @Rub21

**Comment by wronk** [comment]
All done in #159. Thanks @martham93!
