### ISSUE TITLE
Circle CI doesn't sync

### ISSUE THREAD

**Issue by wronk** [developmentseed/label-maker#160]
Circle CI will run automated checks but the status isn't getting properly linked back to GH. Seems like an issue with the CI config file

From CircleCI project page:
> Service alert: Your project references CircleCI 1.0 or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue.

[Upgrade guide](https://circleci.com/sunset1-0/)

**Comment by drewbo** [comment]
CirleCi issue (we are using 2.0 config)
