### ISSUE TITLE
Can i use to extract tiles from google ?

### ISSUE THREAD

**Issue by JKKoffi** [developmentseed/label-maker#174]
Hello! 
Great Thanks for your work!!!
I tried and it worked successfully. 

> I'd like that you let me know if i can use the script to extract tiles from google maps. I'm making some works on google maps tiles to extract buildings of my country. 

> I'd like also that you let me know if we can extract type of buildings, or how can we do to have different buildings.

Thank you in advance!

**Comment by ingalls** [comment]
Hey @JKKoffi while extracting satellite imagery is technically possible, it is unfortunately a violation of the google terms of service. You would need to contact their maps team to get permission to use the tiles and an appropriate API to pull them from.

**Comment by JKKoffi** [comment]
Thanks @ingalls ingalls for these details. I learned also this. 
But, using label-marker , is it possible to identify the type of buildings , or have a category of buildings?

**Comment by ingalls** [comment]
@JKKoffi Not sure I follow what you are asking? Are you asking if Label-Maker will automatically classify buildings for you? Or if you can set it up so that a human user can select between classifications

**Comment by JKKoffi** [comment]
Let me explain you @ingalls, i want to discriminate each building. Is label-marker willing to do it ?

**Comment by JKKoffi** [comment]
But why the tiles from the country that i gave the coordinates in the bounding box are too much poor quality ? The coordinate i used are below: -4.03410418,5.31133473,-4.00415346,5.34186832. The zoom level is 18.
