### ISSUE TITLE
Running label-maker on google colab

### ISSUE THREAD

**Issue by shubhamsharma1609** [developmentseed/label-maker#179]
I have installed label-maker on google colab using **pip install label-maker**. But running a cell with label-maker gives command not found. Please guide how I can run it on google colab.

**Comment by drewbo** [comment]
interactive environments require command line tools to be prefaced with `!`. This should run.
```
!pip install label-maker
!label-maker
```

In general, label-maker will be more difficult to run on Google Colab because it also requires tippecanoe as a peer-dependency.
