### ISSUE TITLE
errors occur when packaging for the two examples (Tanzania and Vietnam)

### ISSUE THREAD

**Issue by giswqs** [developmentseed/label-maker#22]
I ran into problems when testing the two building classification examples (Tanzania and Vietnam) on my Linux machine. All label-maker commands (i.e., `download, labels, preview, images`) worked fine except the `label-maker package` command. 

For the Vietnam example, the `label-maker images` command did download 2296 tiles. However, when using the `label-maker package` command, I got the following errors. I checked the filenames of the titles shown in the error list below and found that they are not among the 2299 tiles downloaded. I had similar issues with the Tanzania example. 

Any help will be appreciated!

************************************* errors *******************************************
(py36) qiusheng@office:/tmp$ label-maker images --dest Vietnam_building --config Vietnam.json
Downloading 2296 tiles to Vietnam_building/tiles
(py36) qiusheng@office:/tmp$ label-maker package --dest Vietnam_building --config Vietnam.json
Couldn't open Vietnam_building/tiles/103935-57783-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104132-57663-17.jpg, skipping
Couldn't open Vietnam_building/tiles/103998-57519-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104007-57744-17.jpg, skipping
Couldn't open Vietnam_building/tiles/103990-57746-17.jpg, skipping
Couldn't open Vietnam_building/tiles/103973-57637-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104061-57529-17.jpg, skipping
Couldn't open Vietnam_building/tiles/103977-57720-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104009-57794-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104224-57747-17.jpg, skipping
......
Couldn't open Vietnam_building/tiles/104194-57708-17.jpg, skipping
Couldn't open Vietnam_building/tiles/104265-57705-17.jpg, skipping
Traceback (most recent call last):
  File "/home/qiusheng/anaconda3/envs/py36/bin/label-maker", line 11, in <module>
    sys.exit(cli())
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/label_maker/main.py", line 87, in cli
    package_directory(dest_folder=dest_folder, **config)
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/label_maker/package.py", line 61, in package_directory
    img = Image.open(image_file)
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Vietnam_building/tiles/104173-57771-17.jpg'

**Comment by Geoyi** [comment]
Hi @giswqs, I think it caused by the tile `104173-57771-17.jpg` doesn't exist in Mapbox imagery, but it was created while running `label-maker images`. The fast way to solve this problem is just `rm Vietnam_building/tiles/104173-57771-17.jpg` and rerun `label-maker package --dest Vietnam_building --config Vietnam.json`. Hope that would solve the issue.

**Comment by giswqs** [comment]
Thanks your tips @Geoyi ! After I removed the following two images, which appeared to be empty images, the `label-maker package` ran successfully, although the 'skipping' warnings still exist. 

Vietnam_building/tiles/104173-57771-17.jpg
Vietnam_building/tiles/104172-57734-17.jpg

**Comment by wronk** [comment]
@Geoyi, @drewbo, should we add a check for empty images?

**Comment by Geoyi** [comment]
yes, @wronk, but they are not empty images actually, they either don't exist in the zoom level or corrupted while they were downloading. I could not completely figure it out yet how that happened, how can we improve this part @drewbo?

**Comment by drewbo** [comment]
We have a [check in the `package` script](https://github.com/developmentseed/label-maker/blob/master/label_maker/package.py#L62) to ensure the image file is there but we should probably catch the similar error of the file not loading with `Image.open` as well (either `OSError` like shown above or `IOError`)

**Comment by giswqs** [comment]
I just tested the Vietnam example on another computer. The `label-maker package` ran successfully without the errors shown above. So I think @Geoyi is probably right about the error source - some image files might be corrupted while downloading.

**Comment by wronk** [comment]
Can confirm that I also got this error (`OSError: cannot identify image file`). Image file technically exists, but looks corrupted and can't be opened. Redownloading images fixed the issue.
