### ISSUE TITLE
Update pylintrc so pylint is less annoying

### ISSUE THREAD

**Issue by wronk** [developmentseed/label-maker#24]
In the pylint rc, we should tell it to ignore some of the warnings we've been manually overriding frequently and we're okay with ignoring.

So far, I'm thinking these:
* global-statement
* too-many-locals 
* too-many-arguments
* too-many-branches

**Comment by wronk** [comment]
I'm happy to do this btw, but probably won't get to it for a week or two

**Comment by drewbo** [comment]
@wronk also `unused-argument` since we pass the whole config to each primary function and catch the extra/unused variables with `**kwargs`
