### ISSUE TITLE
`python setup.py install` causes problems

### ISSUE THREAD

**Issue by wronk** [developmentseed/label-maker#3]
When I install the cloned package using
`python setup.py install`
there were issues importing new submodules I was working on (i.e., python couldn't find them). 

This happened as I was trying to create `label_maker/utils/plot_utils.py` even though I put an empty `__init__.py` file in place and uninstalled/reinstalled the package. Without any changes to the code, `pip install -e .` worked just fine.

**Comment by drewbo** [comment]
I think this is solely related to the name mismatch (`utils`), will reopen if it reoccurs
