### ISSUE TITLE
Object detection example: tfexample_decoder has no attribute 'BackupHandler'

### ISSUE THREAD

**Issue by giswqs** [developmentseed/label-maker#42]
@Geoyi  Thank you for the great [tutorial](https://github.com/developmentseed/label-maker/blob/master/examples/walkthrough-tensorflow-object-detection.md)! I was able to follow through until the very last step to train the object detection model. Before I ran into the error, I had noticed two minor differences from your tutorial:

1. I only got 196 image tiles for the Mexico example instead of 385 image tiles as stated in your tutorial. I did try on two different computers, both of which got the same 196 image titles.
2. The original folder name in the zip file [ssd_inception_v2_coco](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz) is `ssd_inception_v2_coco_2017_11_17`, so I had to change the folder name to `ssd_inception_v2_coco`. You might want to note this in your tutorial. 

I went through the Object Detection Model Setup without any problem. However, when I started to train the model, I got an error `AttributeError: module 'tensorflow.contrib.slim.python.slim.data.tfexample_decoder' has no attribute 'BackupHandler'`, which is similar to the issue reported [here](https://github.com/tensorflow/models/issues/2653). I tried the suggested workaround to download the [tfexample_decoder.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py) and replace my local `tfexample_decoder.py`, but it did not work. It seems the solution is to upgrade to tensorflow v1.4 or a nightly build, which requires cuda 9.0. However, I am not yet ready to upgrade cuda. Any advice will be appreciated! See below for more information about the errors. 

## System information

 **What is the top-level directory of the model you are using:** 

~/tensorflow/models/research/object_detection

**OS Platform and Distribution:** Linux Ubuntu 16.04, Elementary OS

**TensorFlow installed from (source or binary):** pip install tensorflow-gpu

**TensorFlow version**: v1.3.0

**Python version:** v3.6.3

**CUDA/cuDNN version:** CUDA 8.0, cudnn 6.0, nVidia driver: 384.111

**GPU:** nVidia GeForce GTX 1050 Ti 4GB memory

**CPU:** Intel x86-64 Intel Core i7-4790K @ 3.60GHz x 8, 32GB memory

**Exact command to reproduce:**
``` shell
python train.py --logtostderr \
             --train_dir=training/ \
             --pipeline_config_path=training/ssd_inception_v2_coco.config
```

**Source code / logs:**
``` shell
(py36) qiusheng@wu-office:/media/hdd/Data/developmentseed/models/research/object_detection$ python train.py --logtostderr              --train_dir=training/              --pipeline_config_path=training/ssd_inception_v2_coco.config
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    tf.app.run()
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 165, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/media/hdd/Data/developmentseed/models/research/object_detection/trainer.py", line 235, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/media/hdd/Data/developmentseed/models/research/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 122, in get_next
    worker_index=FLAGS.task)).get_next()
  File "/media/hdd/Data/developmentseed/models/research/object_detection/builders/dataset_builder.py", line 140, in build
    label_map_proto_file=label_map_proto_file)
  File "/media/hdd/Data/developmentseed/models/research/object_detection/data_decoders/tf_example_decoder.py", line 153, in __init__
    label_handler = slim_example_decoder.BackupHandler(
AttributeError: module 'tensorflow.contrib.slim.python.slim.data.tfexample_decoder' has no attribute 'BackupHandler'
```
Tried the suggested [workaround](https://github.com/tensorflow/models/issues/2653) to replace the local `tfexample_decoder.py` and got the following error:

``` shell
(py36) qiusheng@wu-office:/media/hdd/Data/developmentseed/models/research/object_detection$ python train.py --logtostderr              --train_dir=training/              --pipeline_config_path=training/ssd_inception_v2_coco.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "/media/hdd/Data/developmentseed/models/research/object_detection/trainer.py", line 32, in <module>
    from object_detection.utils import variables_helper
  File "/media/hdd/Data/developmentseed/models/research/object_detection/utils/variables_helper.py", line 23, in <module>
    slim = tf.contrib.slim
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 60, in <module>
    from tensorflow.contrib import slim
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/slim/__init__.py", line 44, in <module>
    from tensorflow.contrib.slim.python.slim.data import tfexample_decoder
  File "/home/qiusheng/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by Geoyi** [comment]
Hi @giswqs, glad to see you back to try out our TF object detection case as well.
My bad that I kinda use two many bounding boxes for the test case, to answer your question on:
> I only got 196 image tiles for the Mexico example instead of 385 image tiles as stated in your tutorial. I did try on two different computers, both of which got the same 196 image titles.

You might wanna replace the bounding box in your configure file with:
 [-99.17667388916016,19.466430383606728,-99.11865234374999,19.51813278329343]

> The original folder name in the zip file ssd_inception_v2_coco is ssd_inception_v2_coco_2017_11_17, so I had to change the folder name to ssd_inception_v2_coco. You might want to note this in your tutorial.

Actually, the `ssd_inception_v2_coco_2017_11_17.config` is a different file from the folder `ssd_inception_v2_coco_2017_11_17`, you should just download our config file [here](https://github.com/developmentseed/label-maker/blob/master/examples/utils/ssd_inception_v2_coco.config). DON'T change the folder name, otherwise you will need to change the path in the config file as well. 

> `module 'tensorflow.contrib.slim.python.slim.data.tfexample_decoder' has no attribute 'BackupHandler'`

Not sure how this happened, but you might wanna do:

```
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
```
Let me know if you still run into the problems, good luck!!!

**Comment by giswqs** [comment]
@Geoyi Thanks for your hints! I tried your new bounding box, now I got 227 image tiles. Nevermind, now I know what the problem is and I can play with the bounding box. 

Regarding the config file, I did use the provided [`ssd_inception_v2_coco.config`](https://github.com/developmentseed/label-maker/blob/master/examples/utils/ssd_inception_v2_coco.config). What I meant was the folder name within the downloaded zip file [`ssd_inception_v2_coco`](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz). After checking the [`ssd_inception_v2_coco.config`](https://github.com/developmentseed/label-maker/blob/master/examples/utils/ssd_inception_v2_coco.config) Line 152, I realized that I should not have changed the folder name `ssd_inception_v2_coco_2017_11_17`. 

So the folder structure should probably be:
```
models/research/object_detection/
├──ssd_inception_v2_coco_2017_11_17/
├── training/
│   └── ssd_inception_v2_coco.config
├── data/
│   ├── train_buildings.record
│   ├── test_buildings.record
│   └── building_od.pbtxt
└── images/
    ├── train/
    └── test/
```
I guess the folder structure in your tutorial is missing the partial folder name **_2017_11_17**

I have tried every possible way I could, but I still could not by bypass the `'BackupHandler'` error. I guess I have to wait until I upgrade to tensorflow v1.4 and cuda9.0 to test the code again.

**Comment by Geoyi** [comment]
Yay, definitely upgrade your TensorFlow, @giswqs, you should install tensorflow-gpu too, you have GPU backend and it will speed up the training. 
You're completely right about image number 227. That's the number I have to train the model, I tested too many examples, and apparently, one of the examples was too slow and I killed it. 
Thanks for the fact check, and I will definitely update our walkthrough.

**Comment by giswqs** [comment]
@Geoyi finally, I am able to run the code on a Microsoft Azure Linux VM with GPU. It took me a while to install cuda 9.0, cudnn 7.0, python 3.5, tensorflow-gpu 1.5, etc. on a clean Ubuntu Server 16.04. Got all kinds of errors during installation, but I was able to solve them eventually. The training is still running with an average speed of 1 sec/step.

``` shell 
2018-02-16 15:12:54.550821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 6a58:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-02-16 15:12:54.550889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 6a58:00:00.0, compute capability: 3.7)
INFO:tensorflow:Restoring parameters from ssd_inception_v2_coco_2017_11_17/model.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path training/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:global step 1: loss = 297.4543 (14.441 sec/step)
INFO:tensorflow:global step 2: loss = 288.2479 (1.025 sec/step)
INFO:tensorflow:global step 3: loss = 273.9143 (0.980 sec/step)
INFO:tensorflow:global step 4: loss = 259.0708 (0.992 sec/step)
INFO:tensorflow:global step 5: loss = 245.9408 (0.976 sec/step)
INFO:tensorflow:global step 6: loss = 230.3553 (0.992 sec/step)
INFO:tensorflow:global step 7: loss = 220.4153 (1.007 sec/step)
INFO:tensorflow:global step 8: loss = 209.2201 (0.985 sec/step)
INFO:tensorflow:global step 9: loss = 190.2542 (0.969 sec/step)
INFO:tensorflow:global step 10: loss = 172.4187 (1.023 sec/step)
INFO:tensorflow:global step 11: loss = 153.9014 (1.023 sec/step)
INFO:tensorflow:global step 12: loss = 133.6975 (0.998 sec/step)
INFO:tensorflow:global step 13: loss = 122.8432 (0.994 sec/step)
INFO:tensorflow:global step 14: loss = 104.7338 (0.968 sec/step)
INFO:tensorflow:global step 15: loss = 88.5447 (0.979 sec/step)
INFO:tensorflow:global step 16: loss = 83.2795 (1.028 sec/step)
INFO:tensorflow:global step 17: loss = 63.6085 (1.009 sec/step)
INFO:tensorflow:global step 18: loss = 70.0747 (0.981 sec/step)
INFO:tensorflow:global step 19: loss = 51.9096 (0.992 sec/step)
INFO:tensorflow:global step 20: loss = 41.9647 (1.062 sec/step)
INFO:tensorflow:global step 21: loss = 37.5462 (1.002 sec/step)
INFO:tensorflow:global step 22: loss = 29.1385 (1.056 sec/step)
INFO:tensorflow:global step 23: loss = 30.1743 (1.006 sec/step)
INFO:tensorflow:global step 24: loss = 30.5369 (1.019 sec/step)
INFO:tensorflow:global step 25: loss = 30.2714 (1.000 sec/step)
INFO:tensorflow:global step 26: loss = 23.5878 (1.013 sec/step)
...
INFO:tensorflow:global step 21325: loss = 3.0498 (1.088 sec/step)
INFO:tensorflow:global step 21326: loss = 5.0268 (1.092 sec/step)
INFO:tensorflow:global step 21327: loss = 3.2619 (1.051 sec/step)
INFO:tensorflow:global step 21328: loss = 4.2388 (1.068 sec/step)
INFO:tensorflow:global step 21329: loss = 4.5754 (1.079 sec/step)
INFO:tensorflow:global step 21330: loss = 2.8839 (1.060 sec/step)
INFO:tensorflow:global step 21331: loss = 4.7587 (1.059 sec/step)
INFO:tensorflow:global step 21332: loss = 3.1406 (1.045 sec/step)
INFO:tensorflow:global step 21333: loss = 5.1399 (1.081 sec/step)
INFO:tensorflow:global step 21334: loss = 4.9081 (1.038 sec/step)
INFO:tensorflow:global step 21335: loss = 3.0094 (1.041 sec/step)
INFO:tensorflow:global step 21336: loss = 4.7036 (1.154 sec/step)
```

**Comment by Geoyi** [comment]
That's a great news, and thanks for sharing it @giswqs. 
Mine was 12s per step, yours is faster with GPU, can't wait to see how it turns out.

**Comment by drewbo** [comment]
Walkthrough was updated in 086ff8ccdefdab82db1cb51d3802c545ef97e4c1 and 10437027c684aec010ee197cb4abcb7df1a7ffbf
