### ISSUE TITLE
Problem when Create TFRecords from model training

### ISSUE THREAD

**Issue by bobleegogogo** [developmentseed/label-maker#52]
Hallo there,

I got a error : NotfoundError, when I try to creat train_buildings.record like following:
--------------------------------------------------------------------------------------------
hd_hao@DESKTOP-T5OM5NG:/mnt/d/DeepVGI/models/research/object_detection$ python tf_records_generation.py --label_input=labels.npz
You have 211 training tiles and 157 test tiles ready
Traceback (most recent call last):
  File "tf_records_generation.py", line 175, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "tf_records_generation.py", line 142, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.train_rd_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/tf_record.py", line 111, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
----------------------------------------------------------------------------------------
do you guys have any suggestion about this, I am running this on Ubuntu16.04, python3.5

Hao

**Comment by Geoyi** [comment]
Hi @bobleegogogo, 
Do you have the folder called `tiles` under the TOD directory, if so, can you check if all the rgb images and label images are properly downloaded?

**Comment by bobleegogogo** [comment]
Hallo @Geoyi , Yes I do copy the tiles folder under the TOD directory, all the rgb images are properly downloaded. I notice that under the folder images, these rgb images have already be devided into train and test.

**Comment by bobleegogogo** [comment]
Hallo @Geoyi, just I figure out this error since I paste your code from mannual,  everything works now ! I think I made a stupid mistake.

**Comment by Geoyi** [comment]
Glad it worked, @bobleegogogo.

**Comment by bobleegogogo** [comment]
Thanks for your quick help ! This is an amazing walkthrough! @Geoyi
