### ISSUE TITLE
preview fails with: missing 1 required positional argument: 'imagery_offset'

### ISSUE THREAD

**Issue by jreiberkyle** [developmentseed/label-maker#79]
I am running label-maker version 0.3.1.

When I run `label-maker preview -n 3`, the following error is thrown:
```
Traceback (most recent call last):
  File "/opt/conda/bin/label-maker", line 11, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.6/site-packages/label_maker/main.py", line 87, in cli
    preview(dest_folder=dest_folder, number=number, **config)
TypeError: preview() missing 1 required positional argument: 'imagery_offset'
```
I don't see anything in the README or the cli help mentioning `imagery_offset` in regard to the `preview` command.

Some initial digging shows that `preview()` does require imagery_offset as a positional argument. I'm not sure why that isn't being populated.

**Comment by drewbo** [comment]
It's supposed to be optional (for offsetting GeoTIFFs) but I forgot to give a default value for the `preview` function (correct in `images).
