### ISSUE TITLE
Installing label-maker on Ubuntu

### ISSUE THREAD

**Issue by adbedada** [developmentseed/label-maker#86]
I am attempting to install label-maker on Ubuntu and the following error message came up.  Are the dependencies compatable with Linux systems? 

    Using cached https://files.pythonhosted.org/packages/77/d9/d272b38e6e25d2686e22f6058820298dadead69340b1c57ff84c87ef81f0/pycurl-7.43.0.1.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 104, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 841, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 508, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 72, in __init__
        self.configure()
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 108, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'

    Original exception was:
    Traceback (most recent call last):
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 104, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 841, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 508, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 72, in __init__
        self.configure()
      File "/tmp/pip-install-_pmpop_f/pycurl/setup.py", line 108, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    ----------------------------------------
      Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_pmpop_f/pycurl/

**Comment by drewbo** [comment]
Thanks for posting @adbedada! This will probably require some additional dependencies with Linux. Can you try installing libcurl and gcc (`sudo yum install libcurl-devel gcc`) and trying the install again? Once we find out what's missing we can add this to the README. Thanks

**Comment by adbedada** [comment]
Thanks for a quick response @drewbo! After installing libcurl and gcc all dependencies except pyproj and pycurl were installed.  where do you think the issue is stemming from?

Install libcurl and gcc with:

    sudo apt-get install libcurl4-gnutls-dev
    sudo apt-get update
    sudo apt-get install gcc

the error message:  

    Requirement already satisfied: rasterio==1.0a12 in /usr/local/lib/python3.6/dist-packages/rasterio-1.0a12-py3.6-linux-x86_64.egg (from label-maker) (1.0a12)
    Requirement already satisfied: requests==2.11.0 in /usr/local/lib/python3.6/dist-packages/requests-2.11.0-py3.6.egg (from label-maker) (2.11.0)
    Requirement already satisfied: Shapely==1.6.3 in /usr/local/lib/python3.6/dist-packages/Shapely-1.6.3-py3.6-linux-x86_64.egg (from label-maker) (1.6.3)
    Requirement already satisfied: six==1.10.0 in /usr/lib/python3/dist-packages (from label-maker) (1.10.0)
    Requirement already satisfied: tilepie==0.2.1 in /home/adbe/.local/lib/python3.6/site-packages (from label-maker) (0.2.1)
    Requirement already satisfied: certifi in /home/adbe/.local/lib/python3.6/site-packages (from homura==0.1.5->label-maker) (2018.4.16)
    Requirement already satisfied: setuptools in /home/adbe/.local/lib/python3.6/site-packages (from mapbox-vector-tile==1.2.0->label-maker) (39.2.0)
    Requirement already satisfied: future in /home/adbe/.local/lib/python3.6/site-packages (from mapbox-vector-tile==1.2.0->label-maker) (0.16.0)
    Requirement already satisfied: affine in /home/adbe/.local/lib/python3.6/site-packages (from rasterio==1.0a12->label-maker) (2.2.1)
    Requirement already satisfied: attrs in /home/adbe/.local/lib/python3.6/site-packages (from rasterio==1.0a12->label-maker) (18.1.0)
    Requirement already satisfied: click-plugins in /home/adbe/.local/lib/python3.6/site-packages (from rasterio==1.0a12->label-maker) (1.0.3)
    Requirement already satisfied: cligj in /home/adbe/.local/lib/python3.6/site-packages (from rasterio==1.0a12->label-maker) (0.4.0)
    Requirement already satisfied: snuggs>=1.4.1 in /home/adbe/.local/lib/python3.6/site-packages (from rasterio==1.0a12->label-maker) (1.4.2)
    Requirement already satisfied: pyparsing in /home/adbe/.local/lib/python3.6/site-packages (from snuggs>=1.4.1->rasterio==1.0a12->label-maker) (2.2.0)
    Building wheels for collected packages: pycurl, pyproj
    Running setup.py bdist_wheel for pycurl ... error

    .
    .
    .
 
     ----------------------------------------
     Failed building wheel for pyproj
     Running setup.py clean for pyproj
    Failed to build pycurl pyproj
     Installing collected packages: pycurl, pyproj
    Running setup.py install for pycurl ... error
     Complete output from command /usr/bin/python3 -u -c "import setuptools, 
     tokenize;__file__='/tmp/pip-install-4cgzyelf/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gk6bqewv/install-record.txt --single-version-externally-managed --compile:
    Using curl-config (libcurl 7.47.0)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/curl
    copying python/curl/__init__.py -> build/lib.linux-x86_64-3.6/curl
    running build_ext
    building 'pycurl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYCURL_VERSION="7.43.0.1" -DHAVE_CURL_GNUTLS=1 -DHAVE_CURL_SSL=1 -I/usr/include/python3.6m -c src/docstrings.c -o build/temp.linux-x86_64-3.6/src/docstrings.o
    In file included from src/docstrings.c:4:0:
    src/pycurl.h:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
    Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4cgzyelf/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gk6bqewv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4cgzyelf/pycurl/

**Comment by drewbo** [comment]
Still looks like a pycurl issue @adbedada. Can you try [installing that](http://pycurl.io/docs/latest/install.html) on its own and once it's good, installing label-maker?

**Comment by adbedada** [comment]
@drewbo, I tried installing label-maker on different linux machine and noticed that If the system has an existing pycurl module, the installation will be incomplete since pycurl==7.43.0.1 is required. 

      Installing collected packages: pycurl, homura, Shapely, future, pyclipper, protobuf, 
      mapbox-vector-tile, click-plugins, numpy, snuggs, attrs, affine, cligj, rasterio, Pillow, 
      tilepie, mercantile, pyproj, requests, mbutil, label-maker
      ------------
      Found existing installation: pycurl 7.43.0
      Cannot uninstall 'pycurl'. It is a distutils installed project and thus we cannot accurately 
      determine which files belong to it which would lead to only a partial uninstall. 

   Unfortunately,  "pip uninstall pycurl" doesn't work and I'm attempting to see if I can remove pycurl completely and may be install the version required.

**Comment by adbedada** [comment]
Finally... label-maker is now installed after making a couple of changes. Here are the steps.
First, remove the exiting pycurl from the system.
   
    sudo apt-get remove python3-pycurl
    
Before installing it back, do the following.

    sudo apt-cache depends python-pycurl
    sudo apt-get install build-essential libcurl4-gnutls-dev 
    sudo apt-cache search gnutl | grep dev
    sudo apt-get install libgnutls-dev

Then, re-install pycurl

    pip install pycurl==7.43.0.1
     
Now, you can install label-maker with ease.

Thank you @drewbo for your support!

**Comment by caffeine-potent** [comment]
My fix, at the time involved,

**Comment by caffeine-potent** [comment]
I don't recall all of the details of how I got it to run.  
At the very least I remember running these commands:  

```
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libssl-dev
```
