### ISSUE TITLE
Problem with Shapely module?

### ISSUE THREAD

**Issue by moonflash** [developmentseed/label-maker#95]
Following instructions from https://developmentseed.org/blog/2018/01/19/sagemaker-label-maker-case/

Running `label-maker labels --dest vietnam_building --config vietnam.json`
got this error:
```
Retiling QA Tiles to zoom level 17 (takes a bit)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/label_maker/stream_filter.py", line 4, in <module>
    from shapely.geometry import shape, box
ImportError: No module named shapely.geometry
```
Shapely==1.6.3 is installed

I'm on Macos
```
python -V
Python 3.6.4
```

**Comment by drewbo** [comment]
@moonflash can you print the result of running `pip freeze`? Also are you running this from a virtual environment?

**Comment by moonflash** [comment]
@drewbo thanks for feedback.
I'm new to Python (Ruby developer originally) and obviously didn't know enough about the environment.
Now when i've properly used `pyenv` and installed label-maker under python 3.6.3 it all works OK 👍
