### ISSUE TITLE
Couldn't open test_mapbox_imagery/tiles/....jpg, skipping

### ISSUE THREAD

**Issue by joh10891** [developmentseed/label-maker#97]
When I try to run
`label-maker package --dest test_mapbox_imagery --config data.json`
Literally every image file shows up as 
`Couldn't open test_mapbox_imagery/tiles/xxx-xxx-xxx.jpg, skipping`

Additionally, when I try to 
`label-maker preview --dest test_mapbox_imagery --config data.json`
to examine the images, they are unreadable files.

Seems like there's an issue with the satellite imagery files, as all the other steps seem to work. I had seen that some other users had issues with non- existant imagery files, but not sure why none of mine seem to work.

**Comment by drewbo** [comment]
@joh10891 Did you add an API token to your imagery string? Can you show your `data.json` file here?

**Comment by joh10891** [comment]
Yes, added an API token. When I examine the .geojson file, for example, it seems to show the correctly labeled tiles. But the satellite imagery tiles don't appear to be readable. Maybe the user needs special permissions from mapbox to access satellite tiles versus other tiles? Here is how I'm writing the data.json

`# -*- coding: utf-8 -*-
import json

# Make it work for Python 2+3 and with Unicode
import io
try:
    to_unicode = unicode
except NameError:
    to_unicode = str

###DEFINE MAPBOX TOKEN
ACCESS_TOKEN='REDACTED'
  
# Define data
data = {'bounding_box': [-93.403295, 44.246473,
                          -93.253981, 44.332766,],
        'country': 'united_states_of_america',
        'imagery':'http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=ACCESS_TOKEN',
       'classes': [{ "name": "agriculture", "filter": ["has", "landuse", "farmland"] }],
       'ml_type': 'classification',
        'zoom': zoom,
         "background_ratio": 1,
       }

# Write JSON file
with io.open('data.json', 'w', encoding='utf8') as outfile:
    str_ = json.dumps(data,
                      indent=4, sort_keys=True,
                      separators=(',', ': '), ensure_ascii=False)
    outfile.write(to_unicode(str_))

# Read JSON file
with open('data.json') as data_file:
    data_loaded = json.load(data_file)

print(data == data_loaded)`

**Comment by joh10891** [comment]
Perfect, simply replacing the token by putting it directly in, rather than a variable worked perfectly. What a simple mistake on my end! I appreciate the help!
