### ISSUE TITLE
Issue when installing label_maker on Mac OS 

### ISSUE THREAD

**Issue by 15901892** [developmentseed/label-maker#99]
Command used: 

sudo pip install label_maker --ignore-installed six

Here is the error part: 

"/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-xppZNe/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-1yah1H/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-xppZNe/pycurl/

**Comment by drewbo** [comment]
@15901892 let me know if you were able to get this resolved or how I can help

**Comment by drewbo** [comment]
Resolved in person, switched to Anaconda with python 3.6 (previously 3.7 seemed to be having issues with `pyclipper`)
